# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8bc8c7bc77042117c33f60df8a98f346de11abd84fd5c1a4c935d04b18f51c3cb3a9f9bbfb351ce233d00697ffa60c5284bf4940fa913666dbad1809be9e12

test:
  secret_key_base: 9fa752c8690313fc407471b65466dec8fb646f849f5f5ff6d96b942bf89b407c50f1176c0667522c1fe61c80c1760baedd8a25f931fb980c8e2ccf6c2218ea5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
